#基本连接配置信息
spring:
  redis:
    database: 0  #redis库编号 ，redis中提供了16个database，编号为0--15
    host: localhost
#连接池信息
    port: 6379
    jedis:
      pool:
        max-active: 8  #连接池最大连接数
        max-idle: 8     #连接池最大空闲连接数
        max-wait: -1ms  #连接池最大阻塞等待时间，默认-1，表示没有限制
        min-idle: 0     #最小空闲连接数